- README.rst
- robotidy/app.py
- robotidy/cli.py
- robotidy/transformers.py
- tests/utest/test_cli.py
- tests/utest/testdata/config.txt
- tests/utest/testdata/nested/test.robot
- tests/utest/testdata/robotidy.toml
> Config file support

- README.rst
- robotidy/cli.py
- robotidy/decorators.py
- robotidy/transformers.py
- robotidy/utils.py
- tests/atest/transformers/DiscardEmptySections/expected/removes_selected_empty_section.robot
- tests/atest/transformers/ReplaceRunKeywordIf/expected/tests_selected.robot
- tests/atest/transformers/test_transformers.py
- tests/utest/test_cli.py
> Support --start-line and --end-line arguments

- README.rst
- tests/atest/transformers/ExternalTransformer/ExternalTransformer.py
- tests/atest/transformers/ExternalTransformer/expected/tests.robot
- tests/atest/transformers/ExternalTransformer/source/tests.robot
- tests/atest/transformers/test_transformers.py
> increase test coverage for external transformers

- robotidy/transformers.py
- tests/atest/transformers/NormalizeSettingName/expected/selected.robot
- tests/atest/transformers/NormalizeSettingName/expected/tests.robot
- tests/atest/transformers/NormalizeSettingName/source/tests.robot
- tests/atest/transformers/test_transformers.py
> Add NormalizeSettingName transformer

- robotidy/transformers.py
- tests/atest/transformers/NormalizeSectionHeaderName/expected/selected.robot
- tests/atest/transformers/NormalizeSectionHeaderName/expected/tests.robot
- tests/atest/transformers/NormalizeSectionHeaderName/expected/uppercase.robot
- tests/atest/transformers/NormalizeSectionHeaderName/source/tests.robot
- tests/atest/transformers/test_transformers.py
> Add NormalizeSectionHeaderName transformer

- README.rst
- robotidy/cli.py
- robotidy/transformers.py
- tests/utest/test_cli.py
> Add --list-transformers and --describe-transformer cli options

- tests/README.rst
Adds README file describing our tests.
> Add README to tests

- .github/workflows/unit-tests.yml
- robotidy/app.py
- robotidy/cli.py
- robotidy/utils.py
- setup.py
- tests/atest/transformers/ReplaceRunKeywordIf/expected/golden.robot
- tests/atest/transformers/ReplaceRunKeywordIf/expected/tests.robot
- tests/atest/transformers/ReplaceRunKeywordIf/expected/tests_selected.robot
- tests/atest/transformers/ReplaceRunKeywordIf/source/golden.robot
- tests/atest/transformers/ReplaceRunKeywordIf/source/tests.robot
- tests/atest/transformers/test_transformers.py
- tests/utest/test_cli.py
- tests/utest/testdata/check/golden.robot
- tests/utest/testdata/check/not_golden.robot
> Add check option; use RF 4.0

- robotidy/transformers/AlignVariablesSection.py
- robotidy/transformers/__init__.py
- tests/atest/transformers/AlignVariablesSection/expected/optional_equal_sign.robot
- tests/atest/transformers/AlignVariablesSection/expected/tests.robot
- tests/atest/transformers/AlignVariablesSection/source/optional_equal_sign.robot
- tests/atest/transformers/AlignVariablesSection/source/tests.robot
- tests/atest/transformers/test_transformers.py
If you have interesting data that can be used as test data - please share.
> Align variables section transformer

- robotidy/transformers/ReplaceRunKeywordIf.py
- robotidy/utils.py
- tests/atest/transformers/ReplaceRunKeywordIf/expected/tests.robot
- tests/atest/transformers/ReplaceRunKeywordIf/expected/tests_selected.robot
- tests/atest/transformers/ReplaceRunKeywordIf/source/tests.robot
> Fix ReplaceRunKeywordIfs not working if prefixed with BuiltIn

- robotidy/transformers/SmartSortKeywords.py
- robotidy/transformers/__init__.py
- tests/utest/test_cli.py
Thanks for this feature we can make non default transformers (that will run only when using --transformer ThatTransformerName option). 
Closes #10
> Allow to disable transformer by default

- robotidy/transformers/SplitTooLongLine.py
- tests/atest/transformers/SplitTooLongLine/expected/multiple_assignments_on_every_arg.robot
- tests/atest/transformers/SplitTooLongLine/expected/multiple_assignments_until_line_length.robot
- tests/atest/transformers/SplitTooLongLine/source/multiple_assignments.robot
- tests/atest/transformers/test_transformers.py
> Fix SplitTooLongLine keyword eating up multiple assignments

- robotidy/transformers/MergeAndOrderSections.py
- robotidy/transformers/__init__.py
- tests/atest/transformers/MergeAndOrderSections/expected/both_test_and_task.robot
- tests/atest/transformers/MergeAndOrderSections/expected/empty_section.robot
- tests/atest/transformers/MergeAndOrderSections/expected/multiple_header_comments.robot
- tests/atest/transformers/MergeAndOrderSections/expected/nested_block_for.robot
- tests/atest/transformers/MergeAndOrderSections/expected/nested_blocks.robot
- tests/atest/transformers/MergeAndOrderSections/expected/parsing_error.robot
- tests/atest/transformers/MergeAndOrderSections/expected/tests.robot
- tests/atest/transformers/MergeAndOrderSections/source/both_test_and_task.robot
- tests/atest/transformers/MergeAndOrderSections/source/empty_section.robot
- tests/atest/transformers/MergeAndOrderSections/source/multiple_header_comments.robot
- tests/atest/transformers/MergeAndOrderSections/source/nested_block_for.robot
- tests/atest/transformers/MergeAndOrderSections/source/nested_blocks.robot
- tests/atest/transformers/MergeAndOrderSections/source/parsing_error.robot
- tests/atest/transformers/MergeAndOrderSections/source/tests.robot
- tests/atest/transformers/test_transformers.py
Initial version of MergeAndOrderSections transformer.
Closes #70
> MergeAndOrderSections transformer

- robotidy/utils.py
- tests/atest/transformers/AlignSettingsSection/expected/empty_lines.robot
- tests/atest/transformers/AlignSettingsSection/source/empty_lines.robot
- tests/atest/transformers/test_transformers.py
> Fix robotidy breaking on empty lines inside multiline statement

- robotidy/app.py
- robotidy/cli.py
- robotidy/transformers/__init__.py
- tests/utest/test_cli.py
> Robotidy should keep the same order of transformers

- robotidy/transformers/AlignSettingsSection.py
- robotidy/transformers/AlignVariablesSection.py
- tests/atest/transformers/AlignVariablesSection/expected/three_columns.robot
- tests/atest/transformers/AlignVariablesSection/expected/two_columns.robot
- tests/atest/transformers/test_transformers.py
> Allow to align Variables section up_to_column

- robotidy/app.py
- robotidy/utils.py
- setup.py
- tests/utest/test_utils.py
> Fix encoding issues with colorized output

- robotidy/cli.py
- robotidy/utils.py
- tests/utest/test_cli.py
> Remove rst formatting and improve option naming

- CHANGES.md
- README.rst
- robotidy/app.py
- robotidy/cli.py
- robotidy/transformers/__init__.py
- tests/utest/test_cli.py
- tests/utest/testdata/only_pyproject/pyproject.toml
> Add --configure option

- CHANGES.md
- robotidy/transformers/OrderSettings.py
- robotidy/transformers/__init__.py
- tests/atest/transformers/OrderSettings/expected/custom_order_all_end.robot
- tests/atest/transformers/OrderSettings/expected/custom_order_default.robot
- tests/atest/transformers/OrderSettings/expected/custom_order_without_test_teardown.robot
- tests/atest/transformers/OrderSettings/expected/test.robot
- tests/atest/transformers/OrderSettings/source/test.robot
- tests/atest/transformers/test_transformers.py
> Add OrderSettings transformer

- CHANGES.md
- robotidy/transformers/MergeAndOrderSections.py
- robotidy/transformers/OrderSettings.py
- robotidy/transformers/OrderSettingsSection.py
- robotidy/transformers/__init__.py
- tests/atest/transformers/MergeAndOrderSections/expected/tests_without_comment_section.robot
- tests/atest/transformers/OrderSettingsSection/expected/just_comment.robot
- tests/atest/transformers/OrderSettingsSection/expected/last_section.robot
- tests/atest/transformers/OrderSettingsSection/expected/missing_group.robot
- tests/atest/transformers/OrderSettingsSection/expected/parsing_error.robot
- tests/atest/transformers/OrderSettingsSection/expected/test.robot
- tests/atest/transformers/OrderSettingsSection/expected/test_0_newline.robot
- tests/atest/transformers/OrderSettingsSection/expected/test_2_newline.robot
- tests/atest/transformers/OrderSettingsSection/expected/test_empty_group_order.robot
- tests/atest/transformers/OrderSettingsSection/expected/test_group_order.robot
- tests/atest/transformers/OrderSettingsSection/expected/test_missing_group_from_param.robot
- tests/atest/transformers/OrderSettingsSection/expected/test_resource_metadata_first.robot
- tests/atest/transformers/OrderSettingsSection/source/just_comment.robot
- tests/atest/transformers/OrderSettingsSection/source/last_section.robot
- tests/atest/transformers/OrderSettingsSection/source/missing_group.robot
- tests/atest/transformers/OrderSettingsSection/source/parsing_error.robot
- tests/atest/transformers/OrderSettingsSection/source/test.robot
- tests/atest/transformers/test_transformers.py
> Add OrderSettingsSection transformer

- CHANGES.md
- robotidy/cli.py
- tests/utest/test_cli.py
> Fix command option naming

- CHANGES.md
- robotidy/cli.py
- robotidy/transformers/__init__.py
- tests/atest/transformers/RemoveEmptySettings/test_transformer.py
- tests/utest/test_cli.py
> Print description for disabled transformers

- CHANGES.md
- robotidy/transformers/OrderSettings.py
- tests/atest/transformers/OrderSettings/expected/custom_order_all_end.robot
- tests/atest/transformers/OrderSettings/expected/custom_order_default.robot
- tests/atest/transformers/OrderSettings/expected/custom_order_without_test_teardown.robot
- tests/atest/transformers/OrderSettings/expected/test.robot
- tests/atest/transformers/OrderSettings/source/test.robot
> Fix OrderSettings moving all comments after [Teardown] or [Return] statements

- setup.py
> RST -> Markdown in setup.py

- CHANGES.md
- docs/source/transformers/index.rst
- robotidy/api.py
- robotidy/app.py
- robotidy/cli.py
- robotidy/transformers/__init__.py
- tests/utest/test_cli.py
> Robotidy should always use the same order

- CHANGES.md
- docs/source/transformers/ReplaceRunKeywordIf.rst
- robotidy/transformers/ReplaceRunKeywordIf.py
- tests/atest/transformers/ReplaceRunKeywordIf/expected/tests.robot
> Handle missing default ELSE branch in ReplaceRunKeywordIF

- CHANGES.md
- docs/source/configuration/config_file.rst
- robotidy/cli.py
- robotidy/utils.py
- tests/utest/test_cli.py
- tests/utest/testdata/only_pyproject/pyproject.toml
> Allow spaces in pyproject.toml config file

- CHANGES.md
- robotidy/cli.py
- tests/utest/test_cli.py
- tests/utest/testdata/invalid_options_config/pyproject_confgure.toml
- tests/utest/testdata/invalid_options_config/pyproject_idontexist.toml
> Unknown/invalid option names in pyproject.toml file will now cause fatal error

- CHANGES.md
- docs/source/transformers/AlignSettingsSection.rst
- robotidy/transformers/AlignSettingsSection.py
- tests/atest/transformers/AlignSettingsSection/expected/all_columns.robot
- tests/atest/transformers/AlignSettingsSection/expected/multiline_keywords.robot
- tests/atest/transformers/AlignSettingsSection/expected/multiline_keywords_0indent.robot
- tests/atest/transformers/AlignSettingsSection/expected/multiline_keywords_20indent.robot
- tests/atest/transformers/AlignSettingsSection/expected/multiline_keywords_2indent.robot
- tests/atest/transformers/AlignSettingsSection/expected/multiline_keywords_all_col.robot
- tests/atest/transformers/AlignSettingsSection/expected/three_columns.robot
- tests/atest/transformers/AlignSettingsSection/source/multiline_keywords.robot
- tests/atest/transformers/AlignSettingsSection/test_transformer.py
> Add extra indent for arguments when aligning settings section

- CHANGES.md
- robotidy/app.py
> Do not print empty line for file without changes with --diff option

- CHANGES.md
- docs/source/configuration/configuring_transformers.rst
- docs/source/transformers/AlignSettingsSection.rst
- docs/source/transformers/index.rst
- robotidy/transformers/__init__.py
- tests/utest/test_cli.py
> Allow to disable selected transformers

- .github/workflows/unit-tests.yml
- CHANGES.md
- docs/source/configuration/index.rst
- docs/source/external_transformers.rst
- robotidy/api.py
- robotidy/app.py
- robotidy/cli.py
- robotidy/files.py
- setup.py
- tests/README.rst
- tests/utest/test_cli.py
- tests/utest/testdata/gitignore/.gitignore
> Ignore files listed in .gitignore, --exclude and --extend-exclude

- CHANGES.md
- robotidy/transformers/OrderSettingsSection.py
- tests/atest/transformers/OrderSettingsSection/expected/remote_library.robot
- tests/atest/transformers/OrderSettingsSection/source/remote_library.robot
- tests/atest/transformers/OrderSettingsSection/test_transformer.py
> Do not order Remote libraries together with standard libs

- CHANGES.md
- robotidy/api.py
- robotidy/app.py
- robotidy/cli.py
- robotidy/transformers/NormalizeSeparators.py
- robotidy/transformers/RemoveEmptySettings.py
- robotidy/transformers/ReplaceRunKeywordIf.py
- robotidy/transformers/SplitTooLongLine.py
- robotidy/utils.py
- tests/utest/test_api.py
- tests/utest/test_utils.py
Robotframework supports a few different separators, add support for them
> Custom separator

- CHANGES.md
- robotidy/transformers/ReplaceRunKeywordIf.py
- tests/atest/transformers/ReplaceRunKeywordIf/expected/set_variable_workaround.robot
- tests/atest/transformers/ReplaceRunKeywordIf/source/set_variable_workaround.robot
- tests/atest/transformers/ReplaceRunKeywordIf/test_transformer.py
> Remove ELSE branch if it is unnecessary in ReplaceRunKeywordIf

- CHANGES.md
- docs/source/transformers/AlignTestCases.rst
- robotidy/transformers/AlignTestCases.py
- robotidy/transformers/NormalizeNewLines.py
- robotidy/transformers/__init__.py
- robotidy/utils.py
- tasks.py
- tests/atest/transformers/AlignTestCases/expected/for_loops.robot
- tests/atest/transformers/AlignTestCases/expected/no_header_col.robot
- tests/atest/transformers/AlignTestCases/expected/no_header_col_only_headers.robot
- tests/atest/transformers/AlignTestCases/expected/templated_for_loops.robot
- tests/atest/transformers/AlignTestCases/expected/templated_for_loops_and_without.robot
- tests/atest/transformers/AlignTestCases/expected/test.robot
- tests/atest/transformers/AlignTestCases/expected/with_settings.robot
- tests/atest/transformers/AlignTestCases/source/for_loops.robot
- tests/atest/transformers/AlignTestCases/source/no_header_col.robot
- tests/atest/transformers/AlignTestCases/source/templated_for_loops.robot
- tests/atest/transformers/AlignTestCases/source/templated_for_loops_and_without.robot
- tests/atest/transformers/AlignTestCases/source/test.robot
- tests/atest/transformers/AlignTestCases/source/with_settings.robot
- tests/atest/transformers/AlignTestCases/test_transformer.py
- utils/new_transformer_templates/docs.template
- utils/new_transformer_templates/transformer.template
Closes #185 
Also improved templated for autogenerating transformers.
> Align templated test cases

- CHANGES.md
- docs/source/transformers/AddMissingEnd.rst
- robotidy/transformers/AddMissingEnd.py
- robotidy/transformers/__init__.py
- tests/atest/transformers/AddMissingEnd/expected/test.robot
- tests/atest/transformers/AddMissingEnd/expected/test_selected.robot
- tests/atest/transformers/AddMissingEnd/source/test.robot
- tests/atest/transformers/AddMissingEnd/test_transformer.py
- tests/utest/test_cli.py
- tox.ini
> Add AddMissingEnd transformer for loop/if statement missing ENDs

- CHANGES.md
- docs/source/transformers/AddMissingEnd.rst
- docs/source/transformers/AlignSettingsSection.rst
- docs/source/transformers/AlignTestCases.rst
- docs/source/transformers/AlignVariablesSection.rst
- docs/source/transformers/DiscardEmptySections.rst
- docs/source/transformers/MergeAndOrderSections.rst
- docs/source/transformers/NormalizeAssignments.rst
- docs/source/transformers/NormalizeNewLines.rst
- docs/source/transformers/NormalizeSectionHeaderName.rst
- docs/source/transformers/NormalizeSeparators.rst
- docs/source/transformers/NormalizeSettingName.rst
- docs/source/transformers/OrderSettings.rst
- docs/source/transformers/OrderSettingsSection.rst
- docs/source/transformers/RemoveEmptySettings.rst
- docs/source/transformers/RenameKeywords.rst
- docs/source/transformers/RenameTestCases.rst
- docs/source/transformers/ReplaceRunKeywordIf.rst
- docs/source/transformers/SmartSortKeywords.rst
- docs/source/transformers/SplitTooLongLine.rst
- robotidy/transformers/AddMissingEnd.py
- robotidy/transformers/NormalizeAssignments.py
- tests/atest/transformers/NormalizeAssignments/expected/common_equal_sign_variables.robot
- tests/atest/transformers/NormalizeAssignments/expected/common_remove_variables.robot
- tests/atest/transformers/NormalizeAssignments/expected/common_space_and_equal_sign.robot
- tests/atest/transformers/NormalizeAssignments/expected/common_space_and_equal_sign_variables.robot
- tests/atest/transformers/NormalizeAssignments/expected/equal_sign.robot
- tests/atest/transformers/NormalizeAssignments/expected/space_and_equal_sign.robot
- tests/atest/transformers/NormalizeAssignments/source/tests.robot
- tests/atest/transformers/NormalizeAssignments/test_transformer.py
Closes #159 
Also fixes for typos found by @mnojek
> Recognize assignments from *** Variables *** separetly

- robotidy/transformers/AlignTestCases.py
- tests/atest/transformers/AlignTestCases/expected/empty_line.robot
- tests/atest/transformers/AlignTestCases/expected/templated_for_loops_header_cols.robot
- tests/atest/transformers/AlignTestCases/source/empty_line.robot
- tests/atest/transformers/AlignTestCases/source/templated_for_loops_header_cols.robot
- tests/atest/transformers/AlignTestCases/test_transformer.py
> Fix aligning templated test cases with empty lines

- robotidy/files.py
> ignore python files by default

- CHANGES.md
- docs/source/configuration/configuring_transformers.rst
- docs/source/transformers/AlignSettingsSection.rst
- robotidy/transformers/AlignSettingsSection.py
- tests/atest/transformers/AlignSettingsSection/expected/all_columns_fixed.robot
- tests/atest/transformers/AlignSettingsSection/expected/test_fixed.robot
- tests/atest/transformers/AlignSettingsSection/test_transformer.py
#242
#2 (Added recommendation for config)
> Add min_width param to AlignSettingsSection

- CHANGES.md
- docs/source/transformers/AlignTestCases.rst
- robotidy/transformers/AlignTestCases.py
- tests/atest/transformers/AlignTestCases/expected/templated_for_loops_and_without_fixed.robot
- tests/atest/transformers/AlignTestCases/expected/test_fixed.robot
- tests/atest/transformers/AlignTestCases/test_transformer.py
> Add min_width param to AlignTestCases transformer

- CHANGES.md
- docs/source/transformers/DiscardEmptySections.rst
- robotidy/transformers/DiscardEmptySections.py
- tests/atest/transformers/DiscardEmptySections/expected/removes_empty_sections.robot
- tests/atest/transformers/DiscardEmptySections/expected/removes_empty_sections_except_comments.robot
- tests/atest/transformers/DiscardEmptySections/expected/removes_selected_empty_section.robot
- tests/atest/transformers/DiscardEmptySections/source/removes_empty_sections.robot
- tests/atest/transformers/DiscardEmptySections/test_transformer.py
- tests/utest/test_api.py
> Empty sections with only comments are now by defalt not removed

- CHANGES.md
- tests/README.rst
- tests/atest/transformers/AddMissingEnd/test_transformer.py
- tests/atest/transformers/AlignSettingsSection/test_transformer.py
- tests/atest/transformers/AlignTestCases/test_transformer.py
- tests/atest/transformers/AlignVariablesSection/test_transformer.py
- tests/atest/transformers/DiscardEmptySections/test_transformer.py
- tests/atest/transformers/ExternalTransformer/test_transformer.py
- tests/atest/transformers/MergeAndOrderSections/test_transformer.py
- tests/atest/transformers/NormalizeAssignments/test_transformer.py
- tests/atest/transformers/NormalizeNewLines/test_transformer.py
- tests/atest/transformers/NormalizeSectionHeaderName/test_transformer.py
- tests/atest/transformers/NormalizeSeparators/test_transformer.py
- tests/atest/transformers/NormalizeSettingName/test_transformer.py
- tests/atest/transformers/NormalizeTags/test_transformer.py
- tests/atest/transformers/OrderSettings/test_transformer.py
- tests/atest/transformers/OrderSettingsSection/test_transformer.py
- tests/atest/transformers/OrderTags/test_transformer.py
- tests/atest/transformers/RemoveEmptySettings/test_transformer.py
- tests/atest/transformers/RenameKeywords/test_transformer.py
- tests/atest/transformers/RenameTestCases/test_transformer.py
- tests/atest/transformers/ReplaceReturns/test_transformer.py
- tests/atest/transformers/ReplaceRunKeywordIf/test_transformer.py
- tests/atest/transformers/SmartSortKeywords/test_transformer.py
- tests/atest/transformers/SplitTooLongLine/test_transformer.py
- tests/atest/transformers/__init__.py
- utils/new_transformer_templates/test_transformer.template
> Refactor acceptance tests

- CHANGES.md
- robotidy/cli.py
- robotidy/decorators.py
- robotidy/exceptions.py
- robotidy/transformers/AlignVariablesSection.py
- robotidy/transformers/MergeAndOrderSections.py
- robotidy/transformers/NormalizeAssignments.py
- robotidy/transformers/NormalizeSeparators.py
- robotidy/transformers/NormalizeTags.py
- robotidy/transformers/OrderSettings.py
- robotidy/transformers/OrderSettingsSection.py
- robotidy/transformers/RemoveEmptySettings.py
- robotidy/transformers/RenameKeywords.py
- robotidy/transformers/RenameTestCases.py
- robotidy/transformers/__init__.py
- tests/atest/transformers/MergeAndOrderSections/test_transformer.py
- tests/atest/transformers/NormalizeAssignments/test_transformer.py
- tests/atest/transformers/NormalizeSeparators/test_transformer.py
- tests/atest/transformers/NormalizeTags/test_transformer.py
- tests/atest/transformers/OrderSettings/test_transformer.py
- tests/atest/transformers/OrderSettingsSection/test_transformer.py
- tests/atest/transformers/RenameKeywords/test_transformer.py
- tests/atest/transformers/RenameTestCases/test_transformer.py
- tests/utest/test_cli.py
- tox.ini
> Change exceptions to be more user-friendly

- CHANGES.md
- robotidy/app.py
- robotidy/cli.py
- tests/utest/test_cli.py
> Allow to force overwrite files with --check and --overwrite flag

- docs/source/transformers/ReplaceReturns.rst
- robotidy/transformers/ReplaceReturns.py
- tests/atest/transformers/ReplaceReturns/expected/errors.robot
- tests/atest/transformers/ReplaceReturns/expected/run_keyword_and_return.robot
- tests/atest/transformers/ReplaceReturns/expected/run_keyword_and_return_if.robot
RETURN cannot run keywords (at least for now).
> Do not replace Run Keyword with RETURN

- .github/workflows/unit-tests.yml
- robotidy/transformers/MergeAndOrderSections.py
- tests/atest/transformers/MergeAndOrderSections/expected/inline_if.robot
- tests/atest/transformers/MergeAndOrderSections/source/inline_if.robot
- tests/atest/transformers/MergeAndOrderSections/test_transformer.py
- tests/atest/transformers/NormalizeNewLines/expected/inline_if.robot
- tests/atest/transformers/NormalizeNewLines/source/inline_if_0_lines.robot
- tests/atest/transformers/NormalizeNewLines/source/inline_if_1_lines.robot
- tests/atest/transformers/NormalizeNewLines/source/inline_if_2_lines.robot
- tests/atest/transformers/NormalizeNewLines/test_transformer.py
- tests/packages/alpha5/requirements.txt
- tests/packages/recent/requirements.txt
- tests/packages/stable5/requirements.txt
- tox.ini
> Fix MergeAndOrderSections trailing EOL in inline IF handling

- CHANGES.md
- robotidy/api.py
- robotidy/app.py
- robotidy/cli.py
- tests/utest/test_cli.py
- tests/utest/test_utils.py
> Disable coloring the output with --no-color / $ NO_COLOR

- CHANGES.md
- robotidy/transformers/NormalizeNewLines.py
- tests/atest/transformers/NormalizeNewLines/expected/blocks.robot
- tests/atest/transformers/NormalizeNewLines/source/blocks.robot
- tests/atest/transformers/NormalizeNewLines/test_transformer.py
> Normalize empty lines in IF,FOR,WHILE,TRY blocks

- docs/source/transformers/AlignTestCases.rst
- docs/source/transformers/InlineIf.rst
- docs/source/transformers/SplitTooLongLine.rst
Fix typo in command line example mentioned in #295
> Fix configure transformer examples

- CHANGES.md
- docs/source/requirements.txt
- docs/source/transformers/NormalizeSeparators.rst
- noxfile.py
- robotidy/transformers/NormalizeSeparators.py
- setup.py
- tests/atest/transformers/NormalizeSeparators/expected/comment_keywords.robot
- tests/atest/transformers/NormalizeSeparators/expected/comments_settings_variables.robot
- tests/atest/transformers/NormalizeSeparators/expected/skip_documentation.robot
- tests/atest/transformers/NormalizeSeparators/expected/test.robot
- tests/atest/transformers/NormalizeSeparators/expected/test_8spaces.robot
- tests/atest/transformers/NormalizeSeparators/source/test.robot
- tests/atest/transformers/NormalizeSeparators/test_transformer.py
- tests/atest/transformers/__init__.py
- tests/utest/test_utils.py
> Add skip_documentation parameter to NormalizeSeparators

- CHANGES.md
- robotidy/transformers/__init__.py
- tests/atest/transformers/IndentNestedKeywords/source/settings.robot
> Change order of the IndentNestedKeywords

- CHANGES.md
- robotidy/transformers/NormalizeSeparators.py
- tests/atest/transformers/InlineIf/expected/one_if_2spaces.robot
- tests/atest/transformers/InlineIf/expected/one_if_4spaces.robot
- tests/atest/transformers/InlineIf/source/one_if.robot
- tests/atest/transformers/InlineIf/test_transformer.py
- tests/atest/transformers/NormalizeSeparators/expected/inline_if_2indent_2spaces.robot
- tests/atest/transformers/NormalizeSeparators/expected/inline_if_2indent_4spaces.robot
- tests/atest/transformers/NormalizeSeparators/expected/inline_if_4indent_2spaces.robot
- tests/atest/transformers/NormalizeSeparators/source/inline_if.robot
- tests/atest/transformers/NormalizeSeparators/test_transformer.py
> Fix indent handling in inline IFs

- CHANGES.md
- robotidy/app.py
- robotidy/utils.py
- tests/utest/test_utils.py
> Replace click.echo with console.print to support other encodings

- docs/source/transformers/NormalizeTags.rst
> Fix Normalize Tags described as non-default in the docs

- docs/releasenotes/3.0b2.rst
- robotidy/transformers/ReplaceRunKeywordIf.py
- tests/atest/transformers/ReplaceRunKeywordIf/expected/configure_whitespace.robot
- tests/atest/transformers/ReplaceRunKeywordIf/source/configure_whitespace.robot
- tests/atest/transformers/ReplaceRunKeywordIf/test_transformer.py
> Fix ReplaceRunKeywordIf using spacecount instead of indent for indentation

- docs/source/configuration/config_file.rst
- docs/source/configuration/configuring_transformers.rst
> Fix configuration examples in the docs

- docs/_templates/sidebar/brand.html
- docs/source/conf.py
- setup.py
> Change sphinx theme from alabaster to furo

- docs/source/transformers/AlignTemplatedTestCases.rst
> Fix wrong name of transformer in ALignTemplatedTestCases docs:

- CHANGES.md
- docs/releasenotes/3.2.rst
- docs/source/configuration/index.rst
- docs/source/transformers/NormalizeSeparators.rst
> Fix small issues in the docs

- docs/releasenotes/3.2.rst
- docs/source/transformers/AlignSettingsSection.rst
- robotidy/transformers/AlignSettingsSection.py
- tests/atest/transformers/AlignSettingsSection/expected/argument_indents.robot
- tests/atest/transformers/AlignSettingsSection/source/argument_indents.robot
- tests/atest/transformers/AlignSettingsSection/test_transformer.py
> Indent arguments in Settings section for Library and Variables

- docs/releasenotes/3.2.rst
- docs/source/configuration/config_file.rst
> Note for multiline configuration for transform option

- docs/releasenotes/3.2.rst
- robotidy/transformers/__init__.py
- tests/utest/test_load_transformers.py
Mergable after #399
Closes #383
> Warn on duplicate transform

- docs/releasenotes/3.2.rst
- docs/source/transformers/OrderSettings.rst
- robotidy/decorators.py
- robotidy/exceptions.py
- robotidy/transformers/OrderSettings.py
- tests/atest/transformers/OrderSettings/test_transformer.py
> OrderSettings order assertions

- docs/releasenotes/3.2.rst
- docs/source/configuration/skip_formatting.rst
- docs/source/transformers/NormalizeSeparators.rst
- robotidy/cli.py
- robotidy/skip.py
- robotidy/transformers/NormalizeSeparators.py
- tests/atest/transformers/NormalizeSeparators/expected/comments_skip_block_comments.robot
- tests/atest/transformers/NormalizeSeparators/expected/comments_skip_comments.robot
- tests/atest/transformers/NormalizeSeparators/source/comments.robot
- tests/atest/transformers/NormalizeSeparators/test_transformer.py
> Add skip_comments and skip_block_comments options

- docs/source/transformers/index.rst
Related #374 (added info about order of transformers & pipe handling)
> Add info about transformer order to the docs

- docs/releasenotes/3.2.rst
- robotidy/transformers/AlignTemplatedTestCases.py
> Fix AlignTemplatedTestCases with pipes

- docs/releasenotes/3.3.rst
- robotidy/api.py
- robotidy/app.py
- robotidy/cli.py
- robotidy/decorators.py
- robotidy/exceptions.py
- robotidy/rich_console.py
- robotidy/transformers/__init__.py
- robotidy/utils.py
- tests/utest/test_cli.py
> Reorganize import for better support for optional rich dependency

- docs/releasenotes/3.3.rst
- robotidy/cli.py
- tests/utest/test_cli.py
> Add missing --skip-comments option

- docs/releasenotes/3.3.1.rst
- robotidy/transformers/RenameKeywords.py
- tests/atest/transformers/RenameKeywords/expected/embedded_variables.robot
- tests/atest/transformers/RenameKeywords/expected/library_embedded_var_pattern.robot
- tests/atest/transformers/RenameKeywords/expected/rename_pattern_partial.robot
- tests/atest/transformers/RenameKeywords/expected/rename_pattern_whole.robot
- tests/atest/transformers/RenameKeywords/source/embedded_variables.robot
- tests/atest/transformers/RenameKeywords/source/library_embedded_var_pattern.robot
- tests/atest/transformers/RenameKeywords/test_transformer.py
> Do not rename embedded variables in RenameKeywords

- docs/releasenotes/3.4.0.rst
- docs/source/quickstart.rst
- robotidy/cli.py
- robotidy/config.py
- robotidy/transformers/IndentNestedKeywords.py
- robotidy/transformers/__init__.py
- setup.py
- tests/atest/transformers/ExternalTransformer/test_transformer.py
- tests/utest/test_cli.py
> Filter out output of the --list command

- docs/releasenotes/3.5.0.rst
- docs/source/configuration/index.rst
- docs/source/transformers/NormalizeTags.rst
- robotidy/transformers/NormalizeTags.py
- tests/atest/transformers/NormalizeTags/expected/preserve_format_default.robot
- tests/atest/transformers/NormalizeTags/expected/preserve_format_enabled.robot
- tests/atest/transformers/NormalizeTags/source/preserve_format.robot
- tests/atest/transformers/NormalizeTags/test_transformer.py
- tests/e2e/test_transform_stability.py
> Preserve format option in NormalizeTags

- docs/releasenotes/4.0.0.rst
- docs/source/transformers/OrderSettings.rst
- robotidy/transformers/OrderSettings.py
- tests/atest/transformers/OrderSettings/expected/stick_comments.robot
- tests/atest/transformers/OrderSettings/source/stick_comments.robot
- tests/atest/transformers/OrderSettings/test_order_settings.py
> OrderSettings now preserves comments order and groups them with settings

- docs/releasenotes/4.0.0.rst
- docs/source/transformers/SplitTooLongLine.rst
- robotidy/transformers/SplitTooLongLine.py
- tests/atest/transformers/SplitTooLongLine/expected/comments.robot
- tests/atest/transformers/SplitTooLongLine/expected/comments_split_scalar.robot
- tests/atest/transformers/SplitTooLongLine/expected/variables_feed.robot
- tests/atest/transformers/SplitTooLongLine/expected/variables_split_scalar.robot
- tests/atest/transformers/SplitTooLongLine/test_transformer.py
> Do not split single values in SplitTooLongLine transformer

- docs/releasenotes/4.0.0.rst
- docs/source/configuration/skip_formatting.rst
- docs/source/transformers/ReplaceEmptyValues.rst
- robotidy/transformers/ReplaceEmptyValues.py
- robotidy/transformers/__init__.py
- tests/atest/transformers/ReplaceEmptyValues/expected/test.robot
- tests/atest/transformers/ReplaceEmptyValues/source/test.robot
- tests/atest/transformers/ReplaceEmptyValues/test_transformer.py
> Add ReplaceEmptyValues transformer

- docs/source/transformers/SplitTooLongLine.rst
I forgot to indent the code block - fortunately readthedocs always builds whatever is in main branch as latest version and sends notification when build fails.
> Fix failing docs

- docs/releasenotes/4.0.0.rst
- robotidy/transformers/RenameTestCases.py
- tests/atest/transformers/RenameTestCases/expected/replace_pattern_empty.robot
- tests/atest/transformers/RenameTestCases/expected/replace_pattern_placeholder.robot
- tests/atest/transformers/RenameTestCases/expected/replace_pattern_special_chars.robot
- tests/atest/transformers/RenameTestCases/expected/selected.robot
- tests/atest/transformers/RenameTestCases/expected/test.robot
- tests/atest/transformers/RenameTestCases/expected/upper_case.robot
- tests/atest/transformers/RenameTestCases/source/test.robot
> RenameTestCases capitalize each word should now work for words in brackets

- docs/releasenotes/4.0.0.rst
- robotidy/transformers/AlignTemplatedTestCases.py
- tests/atest/transformers/AlignTemplatedTestCases/expected/partly_templated.robot
- tests/atest/transformers/AlignTemplatedTestCases/source/partly_templated.robot
- tests/atest/transformers/AlignTemplatedTestCases/test_transformer.py
> Do not align not templated tests in suite with Test Template

- robotidy/cli.py
- setup.py
> Bump rich click dependency

- docs/releasenotes/4.2.0.rst
- docs/source/configuration/config_file.rst
- robotidy/files.py
- tests/atest/configuration_files/multiple_configs/expected/root/a/.robotidy
- tests/atest/configuration_files/multiple_configs/expected_config_option/root/a/.robotidy
- tests/atest/configuration_files/multiple_configs/source/root/a/.robotidy
> Add new configuration filename - .robotidy

- docs/releasenotes/4.3.0.rst
- robotidy/transformers/IndentNestedKeywords.py
- robotidy/utils.py
- tests/atest/transformers/ReplaceBreakContinue/expected/test.robot
- tests/atest/transformers/ReplaceBreakContinue/source/test.robot
- tests/atest/transformers/ReplaceReturns/expected/return_from_keyword_if.robot
- tests/atest/transformers/ReplaceReturns/expected/return_from_keyword_if_selected.robot
- tests/atest/transformers/ReplaceReturns/source/return_from_keyword_if.robot
> Fix ReplaceBreakContinue and ReplaceReturns failing on multiline statements

- docs/releasenotes/4.3.0.rst
- docs/source/transformers/NormalizeSeparators.rst
- robotidy/transformers/NormalizeSeparators.py
- tests/atest/transformers/AlignTemplatedTestCases/test_transformer.py
- tests/atest/transformers/NormalizeSeparators/expected/cont_indent_align_new_line.robot
- tests/atest/transformers/NormalizeSeparators/expected/continuation_indent.robot
- tests/atest/transformers/NormalizeSeparators/source/continuation_indent.robot
- tests/atest/transformers/NormalizeSeparators/test_transformer.py
- tests/atest/transformers/SplitTooLongLine/expected/align_new_line_all.robot
- tests/atest/transformers/SplitTooLongLine/test_transformer.py
> Add align to new line option to NormalizeSeparators

- docs/releasenotes/4.3.1.rst
- robotidy/transformers/RenameKeywords.py
- tests/atest/transformers/RenameKeywords/expected/bug537.robot
- tests/atest/transformers/RenameKeywords/source/bug537.robot
- tests/atest/transformers/RenameKeywords/test_transformer.py
> Fix RenameKeywords not handling mixed spaces and underscores

- docs/releasenotes/4.4.0.rst
- robotidy/transformers/RenameTestCases.py
- tests/atest/transformers/RenameTestCases/expected/replace_pattern_empty.robot
- tests/atest/transformers/RenameTestCases/expected/replace_pattern_placeholder.robot
- tests/atest/transformers/RenameTestCases/expected/replace_pattern_special_chars.robot
- tests/atest/transformers/RenameTestCases/expected/selected.robot
- tests/atest/transformers/RenameTestCases/expected/test.robot
- tests/atest/transformers/RenameTestCases/expected/upper_case.robot
- tests/atest/transformers/RenameTestCases/source/test.robot
> Fix RenameTestCases renaming words starting with numbers and special chars

- docs/releasenotes/4.4.1.rst
- robotidy/transformers/MergeAndOrderSections.py
- robotidy/transformers/Translate.py
- tests/atest/transformers/MergeAndOrderSections/source/invalid.robot
- tests/atest/transformers/MergeAndOrderSections/test_merge_and_order_sections.py
- tests/atest/transformers/NormalizeSectionHeaderName/source/disablers.robot
- tests/atest/transformers/RenameVariables/expected/test_lower_with_nested.robot
- tests/atest/transformers/RenameVariables/test_transformer.py
- tests/packages/stable6/requirements.txt
- tests/utest/test_load_transformers.py
> Fix issues after backward incompatible changes in RF 6.1

- docs/releasenotes/4.4.1.rst
- robotidy/transformers/NormalizeSeparators.py
- tests/atest/transformers/NormalizeSeparators/expected/inline_if_2indent_2spaces.robot
- tests/atest/transformers/NormalizeSeparators/expected/inline_if_2indent_4spaces.robot
- tests/atest/transformers/NormalizeSeparators/expected/inline_if_4indent_2spaces.robot
- tests/atest/transformers/NormalizeSeparators/expected/inline_if_4indent_4spaces.robot
- tests/atest/transformers/NormalizeSeparators/expected/inline_if_flatten.robot
- tests/atest/transformers/NormalizeSeparators/test_transformer.py
- tests/packages/stable6/requirements.txt
> Fix NormalizeSeparators with flatten_lines=True not handling Infline IFs

- docs/releasenotes/unreleased/fix.1.rst
- robotidy/transformers/AlignVariablesSection.py
- tests/atest/transformers/AlignVariablesSection/expected/single_var.robot
- tests/atest/transformers/AlignVariablesSection/expected/tests_2space_sep.robot
- tests/atest/transformers/AlignVariablesSection/source/single_var.robot
- tests/atest/transformers/AlignVariablesSection/test_transformer.py
> Fix AlignVariablesSection using fixed separator

- docs/releasenotes/unreleased/transfomers.2.rst
- docs/source/transformers/RenameKeywords.rst
- robotidy/transformers/RenameKeywords.py
- tests/atest/transformers/RenameKeywords/expected/capitalize_first.robot
- tests/atest/transformers/RenameKeywords/test_transformer.py
> Configurable RenameKeywords capitalization

- docs/releasenotes/4.9.0.rst
- robotidy/transformers/GenerateDocumentation.py
- tests/atest/transformers/GenerateDocumentation/expected/overwrite.robot
- tests/atest/transformers/GenerateDocumentation/expected/template_with_defaults.robot
- tests/atest/transformers/GenerateDocumentation/expected/test.robot
- tests/atest/transformers/GenerateDocumentation/expected/test_rf4.robot
- tests/atest/transformers/GenerateDocumentation/source/test.robot
> Do not remove docs in settings and tests sections in GenerateDocumentation

- docs/releasenotes/unreleased/fixes.1.rst
- robotidy/app.py
- tests/utest/test_cli.py
- tests/utest/testdata/read_only/test.robot
- tests/utest/utils.py
> Improve file errors handling

- docs/releasenotes/unreleased/fixes.2.rst
- robotidy/transformers/NormalizeTags.py
- tests/atest/transformers/NormalizeTags/expected/variables_in_tags_lowercase.robot
- tests/atest/transformers/NormalizeTags/expected/variables_in_tags_titlecase.robot
- tests/atest/transformers/NormalizeTags/expected/variables_in_tags_uppercase.robot
- tests/atest/transformers/NormalizeTags/source/variables_in_tags.robot
- tests/atest/transformers/NormalizeTags/test_transformer.py
> Fix variables in tag renamed with NormalizeTags

- docs/releasenotes/unreleased/fixes.3.rst
- robotidy/files.py
- robotidy/transformers/NormalizeTags.py
- tests/utest/test_cli.py
- tests/utest/testdata/gitignore/.gitignore
> Fix patterns from gitignore affecting absolute path to project

- docs/releasenotes/unreleased/fixes.4.rst
- robotidy/disablers.py
- robotidy/transformers/NormalizeTags.py
- robotidy/transformers/OrderSettingsSection.py
- robotidy/transformers/RenameKeywords.py
- tests/atest/transformers/NormalizeSeparators/source/disablers2.robot
- tests/atest/transformers/NormalizeSeparators/source/disablers3.robot
- tests/atest/transformers/NormalizeSeparators/source/disablers4.robot
- tests/atest/transformers/NormalizeSeparators/test_transformer.py
- tests/atest/transformers/NormalizeTags/source/disablers2.robot
- tests/atest/transformers/NormalizeTags/source/disablers3.robot
- tests/atest/transformers/NormalizeTags/source/disablers4.robot
- tests/atest/transformers/NormalizeTags/test_transformer.py
> Fix disablers not working for last setting in the section

- docs/releasenotes/unreleased/fixes.1.rst
- robotidy/transformers/ReplaceWithVAR.py
- tests/atest/transformers/ReplaceWithVAR/expected/explicit_local.robot
- tests/atest/transformers/ReplaceWithVAR/expected/replace_catenate_false.robot
- tests/atest/transformers/ReplaceWithVAR/expected/replace_create_dictionary_false.robot
- tests/atest/transformers/ReplaceWithVAR/expected/replace_create_list_false.robot
- tests/atest/transformers/ReplaceWithVAR/expected/replace_set_variable_if_false.robot
- tests/atest/transformers/ReplaceWithVAR/expected/test.robot
- tests/atest/transformers/ReplaceWithVAR/source/test.robot
> Fix empty separator recognized as space in ReplaceWithVAR

- docs/releasenotes/unreleased/fixes.2.rst
- robotidy/transformers/ReplaceWithVAR.py
- tests/atest/transformers/ReplaceWithVAR/expected/explicit_local.robot
- tests/atest/transformers/ReplaceWithVAR/expected/replace_catenate_false.robot
- tests/atest/transformers/ReplaceWithVAR/expected/replace_create_dictionary_false.robot
- tests/atest/transformers/ReplaceWithVAR/expected/replace_create_list_false.robot
- tests/atest/transformers/ReplaceWithVAR/expected/replace_set_variable_if_false.robot
- tests/atest/transformers/ReplaceWithVAR/expected/test.robot
- tests/atest/transformers/ReplaceWithVAR/source/test.robot
> Fix ReplaceWithVAR not supporting Create Dictionary with key and values in a list

- docs/releasenotes/4.11.0.rst
> 4.11.0.rst typo fix

- docs/releasenotes/unreleased/transformers.1.rst
- docs/source/transformers/RenameVariables.rst
- robotidy/transformers/RenameVariables.py
- tests/atest/transformers/RenameVariables/expected/test.robot
- tests/atest/transformers/RenameVariables/expected/test_ignore_camel_case.robot
- tests/atest/transformers/RenameVariables/expected/test_ignore_settings_case.robot
- tests/atest/transformers/RenameVariables/expected/test_ignore_unknown.robot
- tests/atest/transformers/RenameVariables/expected/test_ignore_var_separator.robot
- tests/atest/transformers/RenameVariables/expected/test_lower.robot
- tests/atest/transformers/RenameVariables/expected/test_lower_with_nested.robot
- tests/atest/transformers/RenameVariables/source/test.robot
- tests/atest/transformers/RenameVariables/test_transformer.py
> RenameVariables: Allow to ignore variable separator

- docs/releasenotes/unreleased/transformers.3.rst
- docs/source/transformers/OrderSettings.rst
- robotidy/transformers/OrderSettings.py
- tests/atest/transformers/OrderSettings/expected/custom_order_all_end.robot
- tests/atest/transformers/OrderSettings/expected/custom_order_all_end_pre_rf7.robot
- tests/atest/transformers/OrderSettings/expected/custom_order_default.robot
- tests/atest/transformers/OrderSettings/expected/custom_order_default_pre_rf7.robot
- tests/atest/transformers/OrderSettings/expected/custom_order_without_test_teardown.robot
- tests/atest/transformers/OrderSettings/expected/custom_order_without_test_teardown_pre_rf7.robot
- tests/atest/transformers/OrderSettings/expected/test.robot
- tests/atest/transformers/OrderSettings/expected/test_pre_rf7.robot
- tests/atest/transformers/OrderSettings/source/test.robot
- tests/atest/transformers/OrderSettings/test_order_settings.py
> Add [Setup] to keyword order

- docs/releasenotes/unreleased/transformers.1.rst
- docs/releasenotes/unreleased/transformers.2.rst
- docs/releasenotes/unreleased/transformers.3.rst
- docs/source/transformers/AlignKeywordsSection.rst
- docs/source/transformers/AlignTemplatedTestCases.rst
- docs/source/transformers/AlignTestCasesSection.rst
- robotidy/transformers/AlignKeywordsSection.py
- robotidy/transformers/AlignTestCasesSection.py
- robotidy/transformers/aligners_core.py
- setup.py
- tests/atest/transformers/AlignKeywordsSection/expected/align_settings_separately.robot
- tests/atest/transformers/AlignKeywordsSection/source/align_settings_separately.robot
- tests/atest/transformers/AlignKeywordsSection/test_transformer.py
- tests/atest/transformers/AlignTestCasesSection/expected/settings_auto_separate_settings.robot
- tests/atest/transformers/AlignTestCasesSection/expected/templated_with_setting.robot
- tests/atest/transformers/AlignTestCasesSection/expected/templated_with_settings_auto.robot
- tests/atest/transformers/AlignTestCasesSection/source/templated_with_setting.robot
- tests/atest/transformers/AlignTestCasesSection/test_transformer.py
- tests/utest/test_cli.py
> Align tests with [Template] and align settings separately

- .github/workflows/unit-tests.yml
- README.md
- docs/source/transformers/AlignKeywordsSection.rst
- setup.py
> Fix documentation & update min python version

- docs/releasenotes/unreleased/transformers.2.rst
- robotidy/transformers/RenameVariables.py
- tests/atest/transformers/RenameVariables/expected/test_ignore_var_separator.robot
> Use variable separator when converting variable name from camelCase
