robotidy/app.py
robotidy/cli.py
robotidy/decorators.py
robotidy/transformers.py
tests/utest/test_decorators.py

Implements #4 
We're still in draft phase so all of our code is subject to big changes - but please comment if it's going in good/bad directotion. Every input is welcome!
Added `@transform` decorator - only transformers with this decorator will be automatically loaded (it's step in direction of explicit loading). 
When none transformer is set with `--transform` option robotidy will load all transformer with `@transform` decorator set. Otherwise it will filter out by --transform names.
Added `@configurable` decorator - it behaves similarly as Python property (with the difference that we should return value from our decorated function. Allow to change property value through cli configuration. For example this class:
```
@transformer
class SomeClass:
def __init__(self):
self.my_param = 5 …
```

Make transformers configurable

---

setup.py

Installing `robotframework-tidy` in a clear virtualenv and running `robotidy` produces the following traceback:
```
Traceback (most recent call last):
File "/home/mrmino/.virtualenvs/tmp-97b75d1967920bd/bin/robotidy", line 5, in <module>
from robotidy.cli import cli
File "/home/mrmino/.virtualenvs/tmp-97b75d1967920bd/lib/python3.8/site-packages/robotidy/cli.py", line 12, in <module>
import toml
ModuleNotFoundError: No module named 'toml'
```
This PR fixes that. [The latest version of `toml` as of writing this is 0.10.2](https://pypi.org/project/toml/#history).

Add toml to install_requires

---

.pre-commit-hooks.yaml

Resolves #37. Sorry for being late... again...
This is quite basic. The hook works only on `*.robot` files - pre-commit requires a regex here, as the identification library it uses doesn't recognize RobotFramework source code files. I haven't tested it fully yet, i.e. on all the git hooks it would normally be run by pre-commit.
References: [list of yaml keys with descriptions](https://pre-commit.com/#creating-new-hooks).
A good way of testing it is: `pre-commit try-repo https://github.com/MrMino/robotframework-tidy.git --ref as_precommit_hook --all-files` - this takes the hook straight from the fork under this PR. **Obligatory disclaimer to all, because I'm a chicken :wink: :** do not trust me about it, this command runs the code from my branch (the one from this PR); check it first, I …

Add pre-commit hook manifest file

---

robotidy/transformers/SplitTooLongLine.py

This documentation is displayed if someone runs:
```
robotidy --describe-transformer SplitTooLongLine
```
And also inside our (future) docs. 
It would be nice to get your opinion on doc content since I'm always bad at those :) @MrMino  @mnojek

Add docs to SplitTooLongLine transformer

---

robotidy/transformers/SmartSortKeywords.py
robotidy/transformers/__init__.py
tests/atest/transformers/SmartSortKeywords/expected/empty_before_fist_keyword.robot
tests/atest/transformers/SmartSortKeywords/expected/multiple_sections.robot
tests/atest/transformers/SmartSortKeywords/expected/sort_.robot
tests/atest/transformers/SmartSortKeywords/expected/sort_ci.robot
tests/atest/transformers/SmartSortKeywords/expected/sort_ci_ilu.robot
tests/atest/transformers/SmartSortKeywords/expected/sort_ci_ilu_iou.robot
tests/atest/transformers/SmartSortKeywords/expected/sort_ci_iou.robot
tests/atest/transformers/SmartSortKeywords/expected/sort_ilu.robot
tests/atest/transformers/SmartSortKeywords/expected/sort_ilu_iou.robot
tests/atest/transformers/SmartSortKeywords/expected/sort_iou.robot
tests/atest/transformers/SmartSortKeywords/source/empty_before_fist_keyword.robot
tests/atest/transformers/SmartSortKeywords/source/multiple_sections.robot
tests/atest/transformers/SmartSortKeywords/source/sort_input.robot
tests/atest/transformers/test_transformers.py

New transformer that allows to sort keywords (https://github.com/MarketSquare/robotframework-tidy/issues/52) using following (default behaviour, could be changed) logic:
- sorting is case insensitive
- leading underscores are not ignored, but all other are treated as spaces.
For now there are 2 issues with this PR:
1. If understand correctly right now all transformers are run unless configuration file is present or transformers are selected via command line. I think it would be good to wait until https://github.com/MarketSquare/robotframework-tidy/issues/10 is resolved, so this one will be disabled by default.
2. Test `test_nested_src` is failing for me 7 times out of 8. I would appreciate if you take a look and tell me where I messed up.

Smart Sort Keywords

---

README.rst
robotidy/cli.py
tests/utest/test_cli.py
tests/utest/testdata/config.txt
tests/utest/testdata/invalid_pyproject/pyproject.toml
tests/utest/testdata/only_pyproject/pyproject.toml
tests/utest/testdata/robotidy.toml

Closes #64 
Backward not compatible changes to ``robotidy.toml`` syntax:
- no need for [main] section
- transformers should be described using following code:
```
transform = [
"DiscardEmptySections:allow_only_comments=True",
ReplaceRunKeywordIf
]
```

Add pyproject.toml support

---

robotidy/cli.py
robotidy/decorators.py
robotidy/transformers/RemoveEmptySettings.py
robotidy/transformers/SeparatorNormalizer.py
robotidy/transformers/__init__.py
robotidy/utils.py
tests/atest/transformers/SeparatorNormalizer/expected/pipes.robot
tests/atest/transformers/SeparatorNormalizer/expected/test.robot
tests/atest/transformers/SeparatorNormalizer/expected/test_8spaces.robot
tests/atest/transformers/SeparatorNormalizer/source/pipes.robot
tests/atest/transformers/SeparatorNormalizer/source/test.robot
tests/atest/transformers/test_transformers.py

Closes #32 
Remove support for pipes. It was not supported anyway but there were arguments in CLI that suggested otherwise. SeparatorNormalizer will also replace all pipes to spaces.

Add SeparatorNormalizer transformer

---

CHANGES.md
robotidy/cli.py
robotidy/transformers/__init__.py
robotidy/utils.py
tests/utest/test_cli.py

It works for --transform and --desc options hovewer it doesn't support --configure (it can be extended later). 
Closes #107

Print similar names when using wrong transformer name

---

docs/source/overview.rst

There were some repeated words in the "Documentation" section of the overview.

Minor correction on overview documentation

---

CHANGES.md
robotidy/cli.py
tests/utest/test_cli.py
tests/utest/testdata/robotidy.toml

Fix config not loaded when using --config

---

CHANGES.md
docs/source/configuration/configuring_transformers.rst
docs/source/transformers/ReplaceRunKeywordIf.rst
docs/source/transformers/SmartSortKeywords.rst
robotidy/cli.py
robotidy/transformers/MergeAndOrderSections.py
robotidy/transformers/NormalizeSeparators.py
robotidy/transformers/OrderSettings.py
robotidy/transformers/OrderSettingsSection.py
robotidy/transformers/ReplaceRunKeywordIf.py
robotidy/transformers/SmartSortKeywords.py
tests/atest/transformers/OrderSettings/expected/custom_order_all_end.robot
tests/atest/transformers/OrderSettings/expected/custom_order_default.robot
tests/atest/transformers/OrderSettings/expected/custom_order_without_test_teardown.robot
tests/atest/transformers/OrderSettings/expected/test.robot
tests/atest/transformers/OrderSettings/source/test.robot
tests/atest/transformers/SplitTooLongLine/expected/feed_until_line_length.robot
tests/atest/transformers/SplitTooLongLine/expected/split_on_every_arg.robot
tests/atest/transformers/SplitTooLongLine/source/tests.robot
tests/utest/test_cli.py

Spelling issues found and resolved by [codespell ](https://github.com/codespell-project/codespell) tool. 
There is one more change suggested:
splitted -> split,
but as 'split' is already used along 'splitted' multiple times I did not resolve this in this PR.

spelling fixes

---

CHANGES.md
docs/source/transformers/OrderSettingsSection.rst
robotidy/transformers/OrderSettingsSection.py
tests/atest/transformers/OrderSettingsSection/expected/last_section.robot
tests/atest/transformers/OrderSettingsSection/expected/test.robot
tests/atest/transformers/OrderSettingsSection/expected/test_0_newline.robot
tests/atest/transformers/OrderSettingsSection/expected/test_2_newline.robot
tests/atest/transformers/OrderSettingsSection/expected/test_group_order.robot
tests/atest/transformers/OrderSettingsSection/expected/test_group_order_import_ordered.robot
tests/atest/transformers/OrderSettingsSection/test_transformer.py

Preserve order of imports in OrderSettingsSection

---

robotidy/transformers/RenameKeywords.py
tests/atest/transformers/RenameKeywords/expected/rename_pattern_partial.robot
tests/atest/transformers/RenameKeywords/expected/rename_pattern_whole.robot
tests/atest/transformers/RenameKeywords/expected/test.robot
tests/atest/transformers/RenameKeywords/expected/with_library_name.robot
tests/atest/transformers/RenameKeywords/expected/with_underscores.robot
tests/atest/transformers/RenameKeywords/source/test.robot
tests/atest/transformers/RenameKeywords/source/with_library_name.robot
tests/atest/transformers/RenameKeywords/test_transformer.py

Library part (after before last '.' in name) should now be ignored.
Uppercase only first letter of each word:
Connect to ABC -> Connect To ABC (instead of Connect To Abc)
Related #199

Improve naming handling in RenameKeywords

---

robotidy/cli.py
tests/utest/test_cli.py

exit 1 on No source path provided

---

.codespellrc
CHANGES.md
robotidy/transformers/AddMissingEnd.py
tests/atest/transformers/AddMissingEnd/expected/test.robot
tests/atest/transformers/AddMissingEnd/expected/test_selected.robot
tests/atest/transformers/AddMissingEnd/source/test.robot
tests/atest/transformers/AddMissingEnd/test_transformer.py

Fix statements inside IF only if the END is missing

---

robotidy/transformers/AddMissingEnd.py
robotidy/transformers/AlignVariablesSection.py
robotidy/transformers/InlineIf.py
robotidy/transformers/NormalizeSeparators.py
robotidy/transformers/__init__.py
tests/atest/transformers/__init__.py
tests/utest/test_cli.py

Transformer names were validated when used with ``--transform`` but not with ``--configure``. It means that following command:
```
robotidy --configure InlineI:line_length=100
```
should fail (because of the typo in transformer name) but did not and `InlineIf` was executed without being configured.

Validate transformer names in configuration

---

setup.py

Congratulations on 2.0!
Packaging it [downstream on conda-forge](https://github.com/conda-forge/robotframework-tidy-feedstock/pull/3), it looks like the dependency on `packaging` was not declared on the new release, and the autoformatter moved all the dependencies onto one line.
This PR
- splits and sorts all the dependencies
- like https://github.com/MarketSquare/robotframework-robocop/pull/584
- adds `packaging`
- but only with a bottom pin)
- loosens the `==` pin on `pathspec`
- as a downstream, hard pins are kind of bothersome :blush:

add packaging dependency, split/sort dependencies, loosen hard pin

---

.github/workflows/unit-tests.yml
robotidy/files.py
setup.py
tox.ini

Hi, folks, thanks for `robotframework-tidy`!
This PR replaces use of the unmaintained `toml` with `tomli`, which is both maintained and supports the full `1.0` spec. 
This should tide us over until [PEP-680](https://peps.python.org/pep-0680/) `tomllib`  is widely distributed... but it's probably not worth adding a conditional until python 3.11 is actually released.

use tomli instead of deprecated toml

---

robotidy/disablers.py
robotidy/transformers/AlignKeywordsSection.py
robotidy/transformers/AlignTestCasesSection.py
robotidy/transformers/NormalizeSeparators.py
robotidy/transformers/__init__.py
robotidy/transformers/aligners_core.py
tests/utest/test_disablers.py

Related #310 
Now skip arguments works similarly as ``enabled`` argument - which is accepted by all transformers but it doesn't need to be defined in ``__init__`` of transformer class.
The new logic works in following way:
If any of provided arguments (to transformer) match those handled by Skip.HANDLES set, it will be parsed and then used to create instance of Skip class. If the transformer accept ``skip`` argument, this instance will be passed when creating transformer instance.
Improved our core methods as well and added docs.

Improve Skip argument handling

---

docs/source/configuration/skip_formatting.rst
robotidy/api.py
robotidy/cli.py
robotidy/config.py
robotidy/disablers.py
robotidy/skip.py
robotidy/transformers/__init__.py
tests/utest/test_disablers.py
tests/utest/test_load_transformers.py
tests/utest/test_skip.py
tests/utest/test_utils.py

Closes #310 
Last part of the skip feature - allow to skip formatting globally. 
It's possible to define skips from cli:
```
robotidy --skip-documentation src
```
skip_documentation will apply to all transformers that support this option. If both global and local arguments are provided, the local is overriding global:
```
robotidy --skip-documentation NormalizeSeparators:skip_documentation=False src
```

Define skip parameters globally

---

docs/source/configuration/skip_formatting.rst
docs/source/transformers/AlignKeywordsSection.rst
docs/source/transformers/AlignTestCasesSection.rst
robotidy/config.py
robotidy/transformers/__init__.py
robotidy/transformers/aligners_core.py
tests/atest/transformers/AlignKeywordsSection/expected/simple_auto_ignore_line_4_4_4.robot
tests/atest/transformers/AlignKeywordsSection/expected/simple_fixed_ignore_line_4_4_4.robot
tests/atest/transformers/AlignKeywordsSection/expected/skip_keywords.robot
tests/atest/transformers/AlignKeywordsSection/expected/too_long_line.robot
tests/atest/transformers/AlignKeywordsSection/source/error_node.robot
tests/atest/transformers/AlignKeywordsSection/source/skip_keywords.robot
tests/atest/transformers/AlignKeywordsSection/source/too_long_line.robot
tests/atest/transformers/AlignKeywordsSection/test_transformer.py
tests/atest/transformers/AlignTestCasesSection/expected/simple_auto_ignore_line_4_4_4.robot
tests/atest/transformers/AlignTestCasesSection/expected/simple_fixed_ignore_line_4_4_4.robot
tests/atest/transformers/AlignTestCasesSection/expected/skip_keywords.robot
tests/atest/transformers/AlignTestCasesSection/source/skip_keywords.robot
tests/atest/transformers/AlignTestCasesSection/test_transformer.py

Aligners often aligned code over the line length specified in SplitTooLongLine transformer - but the latter replaced custom,aligned separator with fixed spacing and broke alignment. That's why this PR adds feature to split keyword calls by aligners if aligned line goes over character limit.
It's very useful feature - and to complete I needed to call one transformer from another (which wasn't feasible so far but now open new opportunities). Before every transformer was independent and it wasn't possible. 
Now AlignKeywordsSection and AlignTestCasesSection now check for line length and if it will exceed line length limit the keyword call will be split and then realigned again. This feature will be expanded in next releases (support for other alignes such as AlignSettingsSection or …

Split too long lines in Align Test Case / Keyword Section transformers

---

robotidy/transformers/aligners_core.py
tests/atest/transformers/AlignKeywordsSection/expected/overflow_first_line.robot
tests/atest/transformers/AlignKeywordsSection/expected/too_long_token_counter_compact_overflow.robot
tests/atest/transformers/AlignTestCasesSection/expected/compact_overflow_bug.robot
tests/atest/transformers/AlignTestCasesSection/expected/overflow_first_line.robot
tests/atest/transformers/AlignTestCasesSection/expected/too_long_token_counter_compact_overflow.robot
tests/atest/transformers/AlignTestCasesSection/source/compact_overflow_bug.robot
tests/atest/transformers/AlignTestCasesSection/test_transformer.py

Small edge case: if several tokens in a row didn't fit in column, the ``prev_overflow_len`` didn't carry over. Example (of expected code) in the screenshot:
Now Robotidy carries over the overflow and will finally match with some of the next columns (in the screen it happens with ${LAHETYS} token).
Also removed rounding the separator and token to multiply of four for compact overflow. This is useful if you want to have alignment easy to tabulate into but with compact overflow it's probably not that necessary and it's causing lines to be wider.

Fix compact_overflow failing to align more than two too long columns

---

docs/source/configuration/skip_formatting.rst
docs/source/transformers/AlignKeywordsSection.rst
docs/source/transformers/AlignTestCasesSection.rst
robotidy/api.py
robotidy/cli.py
robotidy/skip.py
robotidy/transformers/AlignKeywordsSection.py
robotidy/transformers/AlignTestCasesSection.py
robotidy/transformers/IndentNestedKeywords.py
robotidy/transformers/aligners_core.py
tests/atest/transformers/AlignKeywordsSection/expected/skip_settings.robot
tests/atest/transformers/AlignKeywordsSection/test_transformer.py
tests/atest/transformers/AlignTestCasesSection/test_transformer.py
tests/utest/test_cli.py

Add skips on settings (``[Arguments]``, ``[Setup]``...). 
Current syntax of the skip allow me to define it freely how I want - but I break DRY principle and I repeat a lot of the code in different places. I'm aware of it and I will refactor it (but it's not in the scope of this PR).

Skip formatting of setting

---

docs/source/configuration/index.rst
docs/source/transformers/AlignKeywordsSection.rst
docs/source/transformers/AlignTestCasesSection.rst
robotidy/transformers/AlignKeywordsSection.py
robotidy/transformers/AlignTestCasesSection.py

Closes #61 . There are few things missing (like aligning of the inline IFs) but it will be tracked separetely.

Add AlignKeywordsSection and AlignTestCasesSection documentation

---

docs/releasenotes/3.0b2.rst
docs/source/transformers/SplitTooLongLine.rst
robotidy/transformers/SplitTooLongLine.py
tests/atest/transformers/SplitTooLongLine/expected/variables_feed.robot
tests/atest/transformers/SplitTooLongLine/expected/variables_split_on_every_value.robot
tests/atest/transformers/SplitTooLongLine/source/variables.robot
tests/atest/transformers/SplitTooLongLine/test_transformer.py

Added long awaited capability of spliting too long variables (up so far ``SplitTooLongLine`` only split too long keyword calls).
Closes #81

Split too long variables

---

docs/releasenotes/3.0b2.rst
docs/source/transformers/AlignKeywordsSection.rst
docs/source/transformers/AlignTestCasesSection.rst
robotidy/transformers/AlignKeywordsSection.py
robotidy/transformers/AlignTestCasesSection.py
robotidy/transformers/aligners_core.py
tests/atest/transformers/AlignKeywordsSection/expected/overflow_first_line.robot
tests/atest/transformers/AlignTestCasesSection/expected/compact_overflow_bug.robot
tests/atest/transformers/AlignTestCasesSection/expected/dynamic_compact_overflow.robot
tests/atest/transformers/AlignTestCasesSection/expected/dynamic_compact_overflow_limit_1.robot
tests/atest/transformers/AlignTestCasesSection/expected/overflow_first_line.robot
tests/atest/transformers/AlignTestCasesSection/source/dynamic_compact_overflow.robot
tests/atest/transformers/AlignTestCasesSection/source/dynamic_compact_overflow_limit_1.robot
tests/atest/transformers/AlignTestCasesSection/test_transformer.py
tests/utest/test_cli.py

Previously aligners with handle_too_long=compact_overflow mode didn't have any limit on misaligned columns. That means if there was situation where too long token could not be "compensated" by breaking alignment of several columns the whole line would be misaligned. Now there is default limit (``compact_overflow_limit = 2``) which will fallback to normal overflow mode if the compact mode breaks the alignment with too many columns in a row.
It's one of the smaller edge cases but we need this update to have truly perfect aligners :)

Improve compact_overflow mode for AlignTestCases/KeywordsSection transformers

---

robotidy/transformers/aligners_core.py
tests/atest/transformers/AlignKeywordsSection/expected/one_column.robot
tests/atest/transformers/AlignKeywordsSection/expected/skip_keywords.robot
tests/atest/transformers/AlignKeywordsSection/expected/skip_return_values.robot
tests/atest/transformers/AlignKeywordsSection/source/skip_return_values.robot
tests/atest/transformers/AlignKeywordsSection/test_transformer.py
tests/atest/transformers/AlignTestCasesSection/expected/one_column.robot
tests/atest/transformers/AlignTestCasesSection/expected/skip_keywords.robot

skip return values option (for aligners) did not truly skip formatting them - it just used fixed separator. This PR improves it and skips the formatting of the return values.
Since our align implementation discarded all whitespace tokens before I had to update it a bit to discard them only after we capture return values (in case we want to skip formatting).

(Truly) skip formatting return values

---

docs/releasenotes/3.1.rst
docs/source/configuration/skip_formatting.rst
docs/source/transformers/SplitTooLongLine.rst
robotidy/transformers/SplitTooLongLine.py
tests/atest/transformers/SplitTooLongLine/expected/skip_keywords.robot
tests/atest/transformers/SplitTooLongLine/test_transformer.py

Now it is possible to skip formatting also with SplitTooLongLine transformer (for example for keywords with given name, that we don't want to split).

Skip formatting of keyword calls in ``SplitTooLongLine`` transformer

---

robotidy/transformers/aligners_core.py
tests/atest/transformers/AlignTestCasesSection/expected/skip_return_values_overflow.robot
tests/atest/transformers/AlignTestCasesSection/source/skip_return_values_overflow.robot
tests/atest/transformers/AlignTestCasesSection/test_transformer.py
tests/e2e/test_transform_stability.py

Fix skip_return_values using too low separator width for overflow column

---

docs/releasenotes/3.2.rst
robotidy/cli.py
tests/utest/test_cli.py

``--target-version`` and ``--transform`` shared the same short name of the option (``-t``). Now ``--target-version`` uses ``-tv``.
I have read on the subject and usually it's not recommended to use more than single character for short name of the option (usually cli tools allow to chains some flags like -l -r can be -lr). But since we're already using two letter short names in both Robocop and Robotidy I went ahead. We don't allow chaining and it's desribed in the docs.
Fixes #375

Fix duplicated short option name for target robot version

---

docs/releasenotes/3.2.rst
robotidy/cli.py
robotidy/config.py
robotidy/transformers/__init__.py
tests/e2e/test_transform_stability.py
tests/utest/test_load_transformers.py

Main change was to store transformer in container class to keep transformer metadata. This allowed us to:
* print transformer parameters and their defaults (Closes #377)
* print transformers in the order they are run
* make some preparation for future refactor of the importing module w- it's getting bit messy!

Print transformer parameters in --desc output

---

docs/releasenotes/3.3.rst
docs/source/configuration/index.rst
robotidy/api.py
robotidy/app.py
robotidy/cli.py
robotidy/config.py
robotidy/utils.py
tests/utest/test_utils.py

Closes #409 (it is not direct implementation of 409, but it does fullfill our needs for language parsing support)

Add --language option to specify file language

---

docs/releasenotes/3.3.rst
robotidy/transformers/NormalizeSeparators.py
tests/atest/transformers/NormalizeSeparators/expected/inline_if_2indent_2spaces.robot
tests/atest/transformers/NormalizeSeparators/expected/inline_if_2indent_4spaces.robot
tests/atest/transformers/NormalizeSeparators/expected/inline_if_4indent_2spaces.robot
tests/atest/transformers/NormalizeSeparators/source/inline_if.robot

Fix separator for BREAK and CONTINUE in infline IF

---

tests/atest/transformers/AddMissingEnd/test_transformer.py
tests/atest/transformers/AlignKeywordsSection/test_transformer.py
tests/atest/transformers/AlignTestCasesSection/test_transformer.py
tests/atest/transformers/MergeAndOrderSections/test_merge_and_order_sections.py
tests/atest/transformers/NormalizeNewLines/test_normalize_new_lines.py
tests/atest/transformers/NormalizeSectionHeaderName/test_normalize_section_header.py
tests/atest/transformers/NormalizeSeparators/test_transformer.py
tests/atest/transformers/NormalizeSettingName/test_normalize_setting_name.py
tests/atest/transformers/OrderSettings/test_order_settings.py
tests/atest/transformers/SplitTooLongLine/test_transformer.py
tests/atest/transformers/__init__.py

Previous solution was flawed - with new major RF version release test set for given version didn't run for new. SpecifierSet allow more flexible approach for defining the test target version.

Use packaging specifier set for tests target version

---

docs/releasenotes/3.3.2.rst
robotidy/transformers/NormalizeTags.py
tests/atest/transformers/NormalizeSettingName/expected/rf6.robot
tests/atest/transformers/NormalizeSettingName/source/rf6.robot
tests/atest/transformers/NormalizeSettingName/test_normalize_setting_name.py
tests/atest/transformers/NormalizeTags/source/rf6.robot
tests/atest/transformers/NormalizeTags/test_transformer.py
tests/e2e/test_transform_stability.py

Do not rename Test Tags to Force Tags

---

docs/releasenotes/3.3.3.rst
robotidy/transformers/RenameKeywords.py
robotidy/transformers/SplitTooLongLine.py
tests/atest/transformers/RenameKeywords/expected/embedded_variables.robot
tests/atest/transformers/RenameKeywords/source/embedded_variables.robot

Fix whitespace in keyword names consisting only of robot variable

---

docs/releasenotes/3.4.0.rst
docs/source/transformers/SplitTooLongLine.rst

The change was already included in #460 but it wasn't mentioned in the documentation.
Closes #456

Skip comments in SplitTooLongLine transformer

---

docs/releasenotes/3.6.0.rst
robotidy/api.py
robotidy/app.py
robotidy/cli.py
robotidy/config.py
tests/e2e/test_transform_stability.py
tests/utest/test_utils.py

This option resolves one of the oldest problems in Robotidy - that sometimes you need to rerun whole tool multiple times since the code keeps changing between runs. This PR introduces new option, --reruns, that allow to configure number of reruns that Robotidy will perform in place until the code stops changing.

Add rerun in place option

---

docs/releasenotes/3.6.0.rst
docs/source/configuration/configuring_transformers.rst
docs/source/external_transformers.rst
robotidy/api.py
robotidy/cli.py
robotidy/config.py
robotidy/transformers/__init__.py
tests/atest/transformers/ExternalTransformer/ExternalDisabledTransformer.py
tests/atest/transformers/ExternalTransformer/expected/tests_lowercase.robot
tests/atest/transformers/ExternalTransformer/expected/tests_only_defaults.robot
tests/atest/transformers/ExternalTransformer/expected/tests_with_defaults.robot
tests/atest/transformers/ExternalTransformer/expected/tests_with_defaults_lowercase.robot
tests/atest/transformers/ExternalTransformer/test_transformer.py
tests/e2e/test_transform_stability.py
tests/utest/test_load_transformers.py
tests/utest/test_utils.py

It implements first part of #476 
New option is added: ``--load-transformers`` which loads custom transformers and runs them after default ones. Before the only option to load custom transformers was to use ``--transform`` which also disabled every other transformer.
The code for importing the transformers got bit ugly but I will refactor it in the seperate PRs - for now I just copied over existing code loading transformers and reused it for ``--load-transformers``. Refactor would change a lot more of the code, making this PR hard to read that's why it will be done separetly.

Load custom transformer on top of default ones

---

docs/releasenotes/4.0.0.rst
robotidy/transformers/__init__.py
tests/atest/transformers/ExternalTransformer/test_transformer.py
tests/utest/test_load_transformers.py

It's actually interesting because I only discovered this issue because I have cloned the tidy repository in the new directory with the space in the name - and external transformers tests started to fail (some of those tests generated absolute path to external transformer file and used it in robotidy config).
I used it as chance to improve upon so now it's also possible to use spaces in the param value too. We had to normalize spaces before with our old design but now it's not needed.

Allow spaces in transformer name or config

---

docs/releasenotes/4.0.0.rst
docs/source/transformers/SplitTooLongLine.rst
robotidy/transformers/SplitTooLongLine.py
tests/atest/transformers/SplitTooLongLine/expected/align_new_line.robot
tests/atest/transformers/SplitTooLongLine/source/align_new_line.robot
tests/atest/transformers/SplitTooLongLine/test_transformer.py

Add option to align new lines to previous line in SplitTooLongLine transformer

---

docs/releasenotes/4.0.0.rst
robotidy/disablers.py
tests/utest/test_disablers.py
tests/utest/testdata/disablers/file_disabled_and_enabled.robot

Implements one of the points from the #479

Allow to disable and enable file starting from the first line

---

docs/releasenotes/4.0.0.rst
docs/source/transformers/NormalizeComments.rst
robotidy/transformers/NormalizeComments.py
robotidy/transformers/__init__.py
tests/atest/transformers/NormalizeComments/expected/test.robot
tests/atest/transformers/NormalizeComments/source/test.robot
tests/atest/transformers/NormalizeComments/test_transformer.py

Add NormalizeComments transformer for fixing space after #

---

docs/releasenotes/4.0.1.rst
robotidy/transformers/__init__.py
tests/utest/test_cli.py
tests/utest/testdata/pyproject_with_src/pyproject.toml

Fixes #504 
Recent improvement that allowed to use spaces in parameter value broke the feature where it was possible to configure transformer with spaces between parameters ("SomeTransformer : param value" in ``pyproject.toml``). This is important enough to be released as a separate fix.

Release 4.0.1: Fix spaces in param:value

---

docs/releasenotes/4.2.0.rst
docs/source/transformers/NormalizeSeparators.rst
robotidy/transformers/NormalizeSeparators.py
robotidy/transformers/aligners_core.py
robotidy/utils.py
tests/atest/transformers/NormalizeSeparators/expected/continuation_indent.robot
tests/atest/transformers/NormalizeSeparators/expected/flatten.robot
tests/atest/transformers/NormalizeSeparators/expected/flatten_rf4.robot
tests/atest/transformers/NormalizeSeparators/source/continuation_indent.robot
tests/atest/transformers/NormalizeSeparators/source/flatten.robot
tests/atest/transformers/NormalizeSeparators/test_transformer.py

Implements one of the features from #507 
Surprisingly there wasn't option to flatten the multilines - any multiline statement was left intact (only the separators changed, unless there was transformer transforming whole statement into something else).

Flatten multilines with NormalizeSeparators

---

docs/releasenotes/4.3.1.rst
robotidy/transformers/RenameKeywords.py
tests/atest/transformers/RenameKeywords/expected/bug537_538.robot
tests/atest/transformers/RenameKeywords/expected/rename_pattern_partial.robot
tests/atest/transformers/RenameKeywords/expected/rename_pattern_whole.robot
tests/atest/transformers/RenameKeywords/expected/test.robot
tests/atest/transformers/RenameKeywords/expected/test_transform_library.robot
tests/atest/transformers/RenameKeywords/expected/with_underscores.robot
tests/atest/transformers/RenameKeywords/source/bug537_538.robot
tests/atest/transformers/RenameKeywords/test_transformer.py

Fixes #538 
I don't like the design of RenameKeywords rename logic but for now I just refactored and simplified it a bit (while fixing a bug).
Because of the refactor, following code:
```
Foo. BAR Baz A B C
```
will not be transformed to:
```
Foo.BAR Baz A B C
```
(it will not be transformed, space after dot will be preserved). I believe it's fine since removing the space after dot wasn't intended behaviour.

Fix RenameKeywords removing underscore after variable

---

docs/releasenotes/unreleased/fixes.4.rst
docs/source/transformers/AlignSettingsSection.rst
docs/source/transformers/AlignVariablesSection.rst
robotidy/transformers/AlignSettingsSection.py
robotidy/transformers/AlignVariablesSection.py
tests/atest/transformers/AlignSettingsSection/expected/test_min_width.robot
tests/atest/transformers/AlignSettingsSection/expected/test_min_width_50_width.robot
tests/atest/transformers/AlignSettingsSection/test_transformer.py
tests/atest/transformers/AlignVariablesSection/expected/tests_min_width.robot
tests/atest/transformers/AlignVariablesSection/expected/tests_min_width_50_width.robot
tests/atest/transformers/AlignVariablesSection/test_transformer.py

For ``AlignVariablesSection`` and ``AlignSettingsSection`` transformers.
Fixes #558

Resolve inconsinstency with min_width working as (not existing before) fixed_width

---

docs/releasenotes/unreleased/fixes.1.rst
robotidy/cli.py
tests/utest/test_cli.py

Read default configuration file in --list command

---

docs/releasenotes/unreleased/other.1.rst
docs/source/configuration/config_file.rst
robotidy/cli.py
robotidy/config.py
robotidy/exceptions.py
robotidy/transformers/ReplaceEmptyValues.py
setup.py
tests/utest/test_cli.py

Generate configuration file

---

.readthedocs.yml

Our documentation build failed because of https://blog.readthedocs.com/use-build-os-config/ (we are quite 'lucky' since today is the first brownout session and another will be in a month)

Fix deprecated readthedocs config

---

robotidy/transformers/InlineIf.py
robotidy/transformers/SplitTooLongLine.py

closes #578
These two innocuous lines meant that processing time increases exponentially with the number of `ELSE IF`s, causing performance issues in specific situations.
I counted the number of visits for each ELSE-IF in my file. There are a total of 30 branches in this file: 1 `IF` followed by 29 `ELSE IF`s. I hashed each keyword node coming through the `visit_KeywordCall` function and counted how often these hashes occurred
```yaml
visitCount: 1
visitCount: 2
visitCount: 5
visitCount: 5
visitCount: 13
visitCount: 13
visitCount: 34
visitCount: 34
visitCount: 34
visitCount: 34
visitCount: 34
visitCount: 34
visitCount: 89
visitCount: 89
visitCount: 233
visitCount: 233
visitCount: 610
visitCount: 610
visitCount: 1597
visitCount: 1597
visitCount: 4181
visitCount: 4181
visitCount: 10946 …
```

Removed redundant fork in AST traversing in SplitTooLongLine

---

docs/releasenotes/4.6.0.rst
docs/source/configuration/config_file.rst
robotidy/exceptions.py
tests/pytest.ini
tests/utest/test_cli.py

Fix wrong robotidy package name in error message

---

docs/releasenotes/unreleased/other.1.rst
robotidy/app.py
tests/utest/test_cli.py

Formatting summary & verbose output

---

setup.py

When robotframework 7 was released the pre-commit hook broke because robotidy didn't support the new major version. This PR limits robotframework requires to version less than 8.0 to prevent robotidy breaking we a new major version of robotframework with breaking changes is released.

Limit robotframework dependency to version less than 8

---

robotidy/app.py
tests/utest/test_cli.py

Currently, files that were skipped would still be counted in the number of reformatted files. This subtracts the number of skipped files from the transformed files and echoes the number of skipped files if any files were skipped.

Add output of number of skipped files

---

tests/atest/transformers/AlignKeywordsSection/expected/documentation_auto_align_first_col.robot
tests/atest/transformers/AlignKeywordsSection/expected/documentation_auto_skip.robot
tests/atest/transformers/AlignKeywordsSection/expected/documentation_fixed_align_first_col.robot
tests/atest/transformers/AlignKeywordsSection/expected/documentation_fixed_skip.robot
tests/atest/transformers/AlignKeywordsSection/source/documentation.robot
tests/atest/transformers/AlignTestCasesSection/expected/documentation_auto_align_first_col.robot
tests/atest/transformers/AlignTestCasesSection/expected/documentation_auto_skip.robot
tests/atest/transformers/AlignTestCasesSection/expected/documentation_fixed_align_first_col.robot
tests/atest/transformers/AlignTestCasesSection/expected/documentation_fixed_skip.robot
tests/atest/transformers/AlignTestCasesSection/source/documentation.robot
tests/atest/transformers/RenameKeywords/test_transformer.py
tests/atest/transformers/SplitTooLongLine/test_transformer.py
tests/utest/test_skip.py

One commit fixes typos; other commit fixes warnings like this one: https://github.com/MarketSquare/robotframework-tidy/actions/runs/8188111566/job/22390024839?pr=661#step:5:96

Reduce codespell and pytest warnings

---

docs/releasenotes/unreleased/fixes.3.rst
robotidy/transformers/SplitTooLongLine.py
tests/atest/transformers/SplitTooLongLine/expected/settings_on_every_arg.robot
tests/atest/transformers/SplitTooLongLine/expected/settings_skip_tests.robot
tests/atest/transformers/SplitTooLongLine/expected/settings_until_line_length.robot
tests/atest/transformers/SplitTooLongLine/expected/settings_until_line_length_skip_comments.robot
tests/atest/transformers/SplitTooLongLine/source/settings.robot
tests/e2e/test_transform_stability.py

Fix SplitTooLongLine not handling invalid keyword name

---

robotidy/app.py
robotidy/cli.py
robotidy/transformers/__init__.py
tests/atest/__init__.py
tests/e2e/test_transform_stability.py
tests/utest/test_cli.py
tests/utest/test_load_transformers.py
tests/utest/utils.py

This splits errors out into stderr. 
It is debatable whether all tests which currently use result.output should be adjusted to explicitly check for stderr vs stdout. I have not yet done so, except to fix the tests that would now echo to stderr.

output errors on the error stream

---

docs/releasenotes/unreleased/fixes.3.rst
docs/releasenotes/unreleased/fixes.4.rst
robotidy/transformers/RenameVariables.py
tests/atest/transformers/RenameVariables/expected/test.robot
tests/atest/transformers/RenameVariables/expected/test_ignore_camel_case.robot
tests/atest/transformers/RenameVariables/expected/test_ignore_settings_case.robot
tests/atest/transformers/RenameVariables/expected/test_ignore_unknown.robot
tests/atest/transformers/RenameVariables/expected/test_lower.robot
tests/atest/transformers/RenameVariables/expected/test_lower_with_nested.robot
tests/atest/transformers/RenameVariables/expected/test_separator_underscore.robot
tests/atest/transformers/RenameVariables/source/test.robot

Handle variables in [Tags] with RenameVariables

---

docs/releasenotes/unreleased/other.1.rst
robotidy/disablers.py
tests/atest/transformers/NormalizeComments/expected/test.robot
tests/atest/transformers/NormalizeComments/source/test.robot
tests/utest/test_disablers.py
tests/utest/testdata/disablers/file_disabled_enabled_in_comments.robot
tests/utest/testdata/disablers/file_disabled_in_comments.robot
tests/utest/testdata/disablers/file_disabled_in_comments_no_header.robot

Acknowledge file disablers in the whole comments section instead of only first line

---

docs/releasenotes/unreleased/fixes.5.rst
docs/releasenotes/unreleased/other.3.rst
docs/releasenotes/unreleased/other.4.rst
docs/source/configuration/disablers.rst
docs/source/configuration/index.rst
docs/source/configuration/skip_formatting.rst
docs/source/quickstart.rst
docs/source/transformers/AlignTestCasesSection.rst

Fix typos, refactor documentation and add missing release notes

---

.github/workflows/code-spell.yml

Depends on #680 
This makes passing spellcheck tests a mandatory requirement for new PRs.

enforce codespell checks in github actions

---

docs/releasenotes/unreleased/fixes.2.rst
docs/releasenotes/unreleased/transformers.2.rst
docs/source/transformers/RenameVariables.rst
robotidy/transformers/RenameVariables.py
tests/atest/transformers/RenameVariables/expected/configure_ignore_vars.robot
tests/atest/transformers/RenameVariables/expected/equal_sign_in_section.robot
tests/atest/transformers/RenameVariables/expected/excluded_vars.robot
tests/atest/transformers/RenameVariables/source/equal_sign_in_section.robot
tests/atest/transformers/RenameVariables/source/excluded_vars.robot
tests/atest/transformers/RenameVariables/test_transformer.py

Fix RenameVariables replacing = with _= and renaming numerical values

---

docs/releasenotes/unreleased/transformers.1.rst
robotidy/transformers/IndentNestedKeywords.py
robotidy/transformers/OrderSettingsSection.py
robotidy/utils/misc.py
tests/atest/transformers/IndentNestedKeywords/expected/comments.robot
tests/atest/transformers/IndentNestedKeywords/source/comments.robot

Ignore comments in formatted Run Keywords
